# Generated by Django 5.0.7 on 2024-07-18 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedbackType', models.CharField(choices=[('Bug', 'Bug'), ('Feature Request', 'Feature Request'), ('General Feedback', 'General Feedback')], max_length=100)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('feedbackDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
