# Generated by Django 5.0.7 on 2024-07-15 19:37

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SoilData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("time", models.TimeField()),
                ("location", models.CharField(max_length=100)),
                ("temperature", models.FloatField()),
                ("humidity", models.FloatField()),
                ("soil_texture", models.CharField(max_length=100)),
                ("rainfall", models.FloatField()),
                ("soil_moisture", models.FloatField()),
            ],
        ),
    ]
